### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/Scratch#11]
![screen shot 2016-01-29 at 14 01 45](https://cloud.githubusercontent.com/assets/8208159/12675137/ddf04792-c690-11e5-9df8-796d5e5d1f53.jpg)

Cred ca doar pe two columns. Testeaza tu te rog daca mai e si pe altele. Daca da, atunci sa le notezi pe toate aici. Daca nu ii dai de cap / te depaseste issue task to @arlad

**Comment by puyaalexxx** [comment]
https://github.com/andreimarin90/Scratch/commit/caa7c2fa0b3ecbdf0979cbcc89e383385ac5907d
