### ISSUE TITLE
home & index-sidebar - slider image

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/Scratch#2]
nu se intinde imaginea
![screenshot_1](https://cloud.githubusercontent.com/assets/12714473/9597930/35e2fc4c-508f-11e5-8dfc-92bce93ecb82.jpg)

**Comment by puyaalexxx** [comment]
https://github.com/andreimarin90/Scratch/commit/15077a691a64fb34919490b44ccc0457c45a9fee
