### ISSUE TITLE
Home & fullwidth - Great Shots – Grid Gallery!

### ISSUE THREAD

**Issue by onuagamer** [andreimarin90/Scratch#3]
imaginile nu au aceeasi dimensiune
![screenshot_2](https://cloud.githubusercontent.com/assets/12714473/9597979/ada198d8-508f-11e5-8ee9-01337cec7033.jpg)

**Comment by andreimarin90** [comment]
@puyaalexxx creaza te rog un add_image_size pentru ele. 

Cand e gata V.1.1.7 si faci push pe FTP, sa task to @onuagamer sa faca regenerate thumbnails.
